using Hexalith.ChatBot.Contracts.Commands;
using Hexalith.ChatBot.Contracts.Enums;

namespace Hexalith.ChatBot.Server.Projections;

internal sealed record AssociationNotification(
    string TenantId,
    string AssociationId,
    string IntakeId,
    string SourceMailboxId,
    string SourceConversationId,
    string? SourceThreadId,
    string? ProjectId,
    string? ProjectDisplayName,
    LifecycleState LifecycleState,
    AssociationScoringOutcome Outcome,
    AssociationThresholdBand ThresholdBand,
    double ConfidenceScore,
    IReadOnlyList<AssociationCandidate> Candidates,
    IReadOnlyList<AssociationExclusion> Exclusions,
    string ThresholdPolicyVersion,
    string DerivationKernelVersion,
    string RedactionState,
    string RetentionClass,
    long SourceVersion,
    DateTimeOffset DetectedAt,
    string CorrelationId,
    AssociationDecisionKind? DecisionKind = null,
    string? DecisionActorId = null,
    string? DecisionActorType = null,
    DateTimeOffset? DecidedAt = null,
    string? DecisionNote = null,
    string? DecisionNoteRedactionState = null,
    string? SurfaceOrigin = null,
    string? PolicySnapshotVersion = null,
    AssociationCorrectionKind? CorrectionKind = null,
    string? PriorProjectId = null,
    string? CorrectedProjectId = null,
    string? PredecessorAssociationId = null,
    string? SupersedesAssociationId = null,
    string? SupersededByAssociationId = null,
    string? CorrectionRationale = null,
    string? CorrectionRationaleRedactionState = null,
    string? CorrectionActorId = null,
    string? CorrectionActorType = null,
    DateTimeOffset? CorrectedAt = null,
    string? DownstreamImpactStatus = null);
