using System.Text.Json.Serialization;

using Hexalith.ChatBot.Contracts.Commands;
using Hexalith.ChatBot.Contracts.Enums;

namespace Hexalith.ChatBot.Server.Projections;

internal sealed record PublishedAssociationEvent(
    [property: JsonPropertyName("tenantId")] string? TenantId,
    [property: JsonPropertyName("domain")] string? Domain,
    [property: JsonPropertyName("aggregateId")] string? AggregateId,
    [property: JsonPropertyName("eventTypeName")] string? EventTypeName,
    [property: JsonPropertyName("sequenceNumber")] long SequenceNumber,
    [property: JsonPropertyName("correlationId")] string? CorrelationId,
    [property: JsonPropertyName("timestamp")] DateTimeOffset Timestamp,
    [property: JsonPropertyName("intakeId")] string? IntakeId,
    [property: JsonPropertyName("sourceMailboxId")] string? SourceMailboxId,
    [property: JsonPropertyName("sourceConversationId")] string? SourceConversationId,
    [property: JsonPropertyName("sourceThreadId")] string? SourceThreadId,
    [property: JsonPropertyName("projectId")] string? ProjectId,
    [property: JsonPropertyName("projectDisplayName")] string? ProjectDisplayName,
    [property: JsonPropertyName("candidates")] IReadOnlyList<AssociationCandidate>? Candidates,
    [property: JsonPropertyName("exclusions")] IReadOnlyList<AssociationExclusion>? Exclusions,
    [property: JsonPropertyName("confidenceScore")] double ConfidenceScore,
    [property: JsonPropertyName("thresholdBand")] AssociationThresholdBand ThresholdBand,
    [property: JsonPropertyName("outcome")] AssociationScoringOutcome? Outcome,
    [property: JsonPropertyName("lifecycleState")] LifecycleState? LifecycleState,
    [property: JsonPropertyName("thresholdPolicyVersion")] string? ThresholdPolicyVersion,
    [property: JsonPropertyName("derivationKernelVersion")] string? DerivationKernelVersion,
    [property: JsonPropertyName("detectedAt")] DateTimeOffset DetectedAt,
    [property: JsonPropertyName("redactionState")] string? RedactionState,
    [property: JsonPropertyName("retentionClass")] string? RetentionClass,
    [property: JsonPropertyName("decisionKind")] AssociationDecisionKind? DecisionKind = null,
    [property: JsonPropertyName("actorId")] string? ActorId = null,
    [property: JsonPropertyName("actorType")] string? ActorType = null,
    [property: JsonPropertyName("decidedAt")] DateTimeOffset? DecidedAt = null,
    [property: JsonPropertyName("decisionNote")] string? DecisionNote = null,
    [property: JsonPropertyName("decisionNoteRedactionState")] string? DecisionNoteRedactionState = null,
    [property: JsonPropertyName("surfaceOrigin")] string? SurfaceOrigin = null,
    [property: JsonPropertyName("policySnapshotVersion")] string? PolicySnapshotVersion = null,
    [property: JsonPropertyName("candidateProjectIds")] IReadOnlyList<string>? CandidateProjectIds = null,
    [property: JsonPropertyName("evidenceRefs")] IReadOnlyList<AssociationEvidenceReference>? EvidenceRefs = null,
    [property: JsonPropertyName("confidenceInputs")] IReadOnlyList<AssociationConfidenceInput>? ConfidenceInputs = null,
    [property: JsonPropertyName("correctionKind")] AssociationCorrectionKind? CorrectionKind = null,
    [property: JsonPropertyName("priorProjectId")] string? PriorProjectId = null,
    [property: JsonPropertyName("correctedProjectId")] string? CorrectedProjectId = null,
    [property: JsonPropertyName("predecessorAssociationId")] string? PredecessorAssociationId = null,
    [property: JsonPropertyName("supersedesAssociationId")] string? SupersedesAssociationId = null,
    [property: JsonPropertyName("supersededByAssociationId")] string? SupersededByAssociationId = null,
    [property: JsonPropertyName("correctionRationale")] string? CorrectionRationale = null,
    [property: JsonPropertyName("correctionRationaleRedactionState")] string? CorrectionRationaleRedactionState = null,
    [property: JsonPropertyName("correctionActorId")] string? CorrectionActorId = null,
    [property: JsonPropertyName("correctionActorType")] string? CorrectionActorType = null,
    [property: JsonPropertyName("correctedAt")] DateTimeOffset? CorrectedAt = null,
    [property: JsonPropertyName("downstreamImpactStatus")] string? DownstreamImpactStatus = null,
    [property: JsonPropertyName("correctionId")] string? CorrectionId = null,
    [property: JsonPropertyName("workflowInstanceId")] string? WorkflowInstanceId = null,
    [property: JsonPropertyName("requiredStoreKeys")] IReadOnlyList<string>? RequiredStoreKeys = null,
    [property: JsonPropertyName("completedStoreKeys")] IReadOnlyList<string>? CompletedStoreKeys = null,
    [property: JsonPropertyName("storeKey")] string? StoreKey = null,
    [property: JsonPropertyName("storeOutcome")] string? StoreOutcome = null,
    [property: JsonPropertyName("failureReasonCode")] string? FailureReasonCode = null,
    [property: JsonPropertyName("startedAtUtc")] DateTimeOffset? PropagationStartedAtUtc = null,
    [property: JsonPropertyName("completedAtUtc")] DateTimeOffset? PropagationCompletedAtUtc = null,
    [property: JsonPropertyName("estimatedCompletionAtUtc")] DateTimeOffset? PropagationEstimatedCompletionAtUtc = null,
    [property: JsonPropertyName("responsibleOwnerRole")] string? ResponsibleOwnerRole = null,
    [property: JsonPropertyName("nextSafeAction")] string? SafeNextAction = null);
