using Hexalith.ChatBot.Contracts.Enums;

namespace Hexalith.ChatBot.Server.Projections;

internal sealed record PublishedApprovalEvent(
    string TenantId,
    string Domain,
    string AggregateId,
    long SourceVersion,
    DateTimeOffset OccurredAtUtc,
    string CorrelationId,
    string ProjectId,
    string ApprovalId,
    ApprovalEventKind EventKind,
    ApprovalStatus Status,
    string? ProposalId = null,
    string? SourceMessageId = null,
    string? SourceConversationItemId = null,
    string? RequesterId = null,
    string? RequesterActorType = null,
    DateTimeOffset? RequestedAtUtc = null,
    string? CommandName = null,
    string? CommandAllowlistVersion = null,
    RiskClass? RiskClass = null,
    IReadOnlyList<string>? RiskActionClasses = null,
    string? PolicySnapshotId = null,
    string? PolicySnapshotVisibility = null,
    IReadOnlyList<string>? EvidenceReferences = null,
    IReadOnlyList<ApprovalEvidenceFreshness>? EvidenceFreshnessStates = null,
    IReadOnlyList<string>? AffectedResourceReferences = null,
    IReadOnlyList<string>? RecipientReferences = null,
    string? SenderAuthorityClass = null,
    string? ExpectedPostStateRedactionState = null,
    string? ActionSummaryRedactionState = null,
    ApprovalDecisionKind? DecisionKind = null,
    string? DecisionActorId = null,
    string? DecisionActorType = null,
    DateTimeOffset? DecidedAtUtc = null,
    string? AuthorityResult = null,
    string? DisabledReason = null,
    string? DecisionRationaleRedactionState = null,
    string? AuditOperationId = null,
    string? AuditStatus = null,
    string? CommandOutcomeStatus = null,
    DateTimeOffset? OutcomeAtUtc = null,
    string? ProjectedOutcomeItemId = null,
    string? FailureCode = null,
    string? Retryability = null,
    string? SupersedesApprovalId = null,
    string? SupersededByApprovalId = null,
    string? SafeNextAction = null,
    string RedactionState = "metadata_only",
    string RetentionClass = "collaboration_input");
