using Hexalith.ChatBot.Contracts.Enums;
using Hexalith.ChatBot.Contracts.Messages;

namespace Hexalith.ChatBot.Server.Projections;

internal sealed record PublishedFailureStateEvent(
    string TenantId,
    string Domain,
    string AggregateId,
    long SourceVersion,
    DateTimeOffset OccurredAtUtc,
    string CorrelationId,
    string ProjectId,
    FailureStateKind FailureStateKind,
    FailureStatus FailureStatus,
    string MessageCatalogCode,
    string OperationId,
    string? SourceConversationItemId = null,
    string? AssociationId = null,
    string? SourceMessageId = null,
    string? WorkflowInstanceId = null,
    string? SupersedesWorkflowInstanceId = null,
    string? SupersededByWorkflowInstanceId = null,
    string? TaskId = null,
    string? AuditOperationId = null,
    string? AuditStatus = null,
    string? ClientAction = null,
    string? FailureCategory = null,
    string? FailureScope = null,
    string? FailureReasonCode = null,
    string? BlockedReason = null,
    bool? Retryable = null,
    int? RetryCount = null,
    int? MaxRetryCount = null,
    DateTimeOffset? NextRetryAtUtc = null,
    DateTimeOffset? LastRetryAtUtc = null,
    string? RetryOperationId = null,
    string? SafeNextAction = null,
    string? DuplicateSafetyState = null,
    string? DuplicateSuppressionId = null,
    string? DependencyName = null,
    DateTimeOffset? DegradedUntilUtc = null,
    string? EscalationTargetRole = null,
    string? ReprocessCreatedWorkflowInstanceId = null,
    string RedactionState = ChatBotDetailVisibility.MetadataOnly,
    string RetentionClass = "collaboration_input");
