# DAPR Secret Store -- Memories Server (Local Development)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "DaprComponents/secrets.memories.json"
    - name: nestedSeparator
      value: ":"
