namespace Hexalith.ChatBot.UI.State.ProjectConversation;

public sealed record ProjectConversationModel(
    string ProjectId,
    string ProjectDisplayName,
    string? TenantContext,
    string Status,
    string ConversationState,
    IReadOnlyList<ProjectConversationItemModel> Items,
    string? NextCursor,
    bool HasMore,
    int PageSize,
    string SourceProvenance,
    string RedactionState,
    string RetentionClass,
    string SchemaVersion,
    string CorrelationId,
    string SafeNextAction)
{
    public bool IsEmpty => Items.Count == 0;

    public bool IsBlockedOrStale => Status is "Blocked" or "Stale" or "Degraded";
}

public sealed record ProjectAssociationWhyPanelModel(
    string ProjectId,
    string AssociationId,
    string IntakeId,
    string SourceMailboxId,
    string SourceConversationId,
    string? SourceThreadId,
    string LifecycleState,
    string Outcome,
    string ThresholdBand,
    double ConfidenceScore,
    string ThresholdPolicyVersion,
    string KernelVersion,
    DateTimeOffset DecisionTimestamp,
    string? DecisionActorId,
    string? DecisionActorType,
    string SourceProvenance,
    string RedactionState,
    string SchemaVersion,
    long SourceVersion,
    string CorrelationId,
    IReadOnlyList<string> ReasonCodes,
    IReadOnlyList<ProjectAssociationWhyEvidenceModel> Evidence,
    string? PriorProjectId,
    string? CorrectedProjectId,
    string? PredecessorAssociationId,
    string? SupersedesAssociationId,
    string? SupersededByAssociationId,
    string? SupersedingCorrectionId,
    string? SupersedingCorrectionLink,
    bool CorrectionPanelAvailable,
    string? PropagationStatus,
    string? DownstreamImpactStatus,
    bool IsCorrectedContextStale,
    string SafeNextAction)
{
    public bool IsEmpty => Evidence.Count == 0;
}

public sealed record ProjectAssociationWhyEvidenceModel(
    string Kind,
    string? SignalClass,
    string DisplayToken,
    string Fingerprint,
    string Reference,
    string VisibilityState,
    string RedactionState,
    string FreshnessState,
    double? ConfidenceContribution);

public sealed record ProjectConversationItemModel(
    string ItemId,
    string Kind,
    string ActorKind,
    string ActorLabel,
    DateTimeOffset OccurredAt,
    string LifecycleState,
    string ThresholdBand,
    double ConfidenceScore,
    string AssociationId,
    string SourceMailboxId,
    string? SourceProviderMessageId,
    string? InternetMessageId,
    string SourceConversationId,
    string? SourceThreadId,
    DateTimeOffset? SourceReceivedAtUtc,
    DateTimeOffset? SourceSentAtUtc,
    DateTimeOffset? SourceCreatedAtUtc,
    string? SourceTimezone,
    string? SourceProvenanceDisplayToken,
    string SourceProvenance,
    string RedactionState,
    string RetentionClass,
    string SchemaVersion,
    long SourceVersion,
    string CorrelationId,
    string? ProjectId,
    string? ProjectDisplayName,
    string? DecisionLabel,
    string? SafeNextAction,
    string? ParticipantResolutionId,
    string? SourceParticipantId,
    string? PartyId,
    string? ParticipantStatus,
    string? ParticipantBlockedReason,
    string? ParticipantDisplayKind,
    string? ParticipantEvidenceReference,
    string? ParticipantEvidenceFingerprint,
    IReadOnlyList<string> ParticipantAllowedReviewActions,
    string? ParticipantRedactionState,
    string? SourceProviderAttachmentId,
    string? AttachmentDisplayName,
    string? AttachmentContentType,
    long? AttachmentSizeInBytes,
    string? AttachmentCaptureStatus,
    string? AttachmentStorageStatus,
    string? AttachmentScanStatus,
    string? AttachmentFolderId,
    string? AttachmentFileId,
    string? AttachmentDuplicateState,
    string? AttachmentRetryState,
    string? AttachmentAiContextEligibility,
    IReadOnlyList<string> AttachmentAllowedActions,
    string? AttachmentRedactionState,
    string? DecisionKind,
    string? DecisionActorId,
    string? DecisionActorType,
    DateTimeOffset? DecidedAtUtc,
    string? DecisionNoteRedactionState,
    string? SurfaceOrigin,
    string? PolicySnapshotVersion,
    IReadOnlyList<string> EvidenceReferenceSummary,
    string? CorrectionKind,
    string? PriorProjectId,
    string? CorrectedProjectId,
    string? PredecessorAssociationId,
    string? SupersedesAssociationId,
    string? SupersededByAssociationId,
    string? CorrectionRationaleRedactionState,
    string? CorrectionActorId,
    string? CorrectionActorType,
    DateTimeOffset? CorrectedAtUtc,
    string? DownstreamImpactStatus,
    string? CorrectionId,
    string? WorkflowInstanceId,
    IReadOnlyList<string> RequiredStoreKeys,
    IReadOnlyList<string> CompletedStoreKeys,
    IReadOnlyList<string> FailedStoreKeys,
    int? PropagationProgressNumerator,
    int? PropagationProgressDenominator,
    DateTimeOffset? PropagationStartedAtUtc,
    DateTimeOffset? PropagationCompletedAtUtc,
    DateTimeOffset? PropagationEstimatedCompletionAtUtc,
    string? PropagationStatus,
    bool? IsCorrectedContextStale,
    string? ResponsibleOwnerRole,
    string? ApprovalId,
    string? ApprovalEventKind,
    string? ApprovalStatus,
    string? ApprovalDecisionKind,
    string? ApprovalRequesterId,
    string? ApprovalRequesterActorType,
    DateTimeOffset? ApprovalRequestedAtUtc,
    string? ApprovalDecisionActorId,
    string? ApprovalDecisionActorType,
    DateTimeOffset? ApprovalDecidedAtUtc,
    DateTimeOffset? ApprovalOutcomeAtUtc,
    string? ApprovalProposalId,
    string? ApprovalSourceMessageId,
    string? ApprovalSourceConversationItemId,
    string? ApprovalCommandName,
    string? ApprovalCommandAllowlistVersion,
    string? ApprovalRiskClass,
    IReadOnlyList<string> ApprovalRiskActionClasses,
    string? ApprovalAiRiskClass,
    IReadOnlyList<string> ApprovalAiRiskActionClasses,
    string? ApprovalAiRiskInputTuple,
    string? ApprovalPolicySnapshotId,
    string? ApprovalPolicySnapshotVisibility,
    IReadOnlyList<string> ApprovalEvidenceReferences,
    IReadOnlyList<string> ApprovalEvidenceFreshnessStates,
    IReadOnlyList<string> ApprovalAffectedResourceReferences,
    IReadOnlyList<string> ApprovalRecipientReferences,
    string? ApprovalSenderAuthorityClass,
    string? ApprovalExpectedPostStateRedactionState,
    string? ApprovalActionSummaryRedactionState,
    string? ApprovalDecisionRationaleRedactionState,
    string? ApprovalAuthorityResult,
    string? ApprovalDisabledReason,
    string? ApprovalAuditOperationId,
    string? ApprovalAuditStatus,
    string? ApprovalCommandOutcomeStatus,
    string? ApprovalProjectedOutcomeItemId,
    string? ApprovalFailureCode,
    string? ApprovalRetryability,
    string? SupersedesApprovalId,
    string? SupersededByApprovalId,
    string? FailureStateKind,
    string? FailureStatus,
    string? MessageCatalogCode,
    string? MessageCatalogVersion,
    string? MessageDetailVisibility,
    string? FailureCategory,
    string? FailureScope,
    string? FailureReasonCode,
    string? BlockedReason,
    bool? Retryable,
    int? RetryCount,
    int? MaxRetryCount,
    DateTimeOffset? NextRetryAtUtc,
    DateTimeOffset? LastRetryAtUtc,
    string? RetryOperationId,
    string? SupersedesWorkflowInstanceId,
    string? SupersededByWorkflowInstanceId,
    string? TaskId,
    string? OperationId,
    string? AuditOperationId,
    string? AuditStatus,
    string? ClientAction,
    string? DuplicateSafetyState,
    string? DuplicateSuppressionId,
    string? DependencyName,
    DateTimeOffset? DegradedUntilUtc,
    string? EscalationTargetRole,
    string? ReprocessCreatedWorkflowInstanceId,
    string? AiOutcomeKind = null,
    string? AiOutcomeStatus = null,
    string? AiActorId = null,
    string? AiActorType = null,
    string? AiProposalId = null,
    string? AiRequestId = null,
    string? AiRequesterId = null,
    string? AiSourceConversationItemId = null,
    string? AiSourceMessageId = null,
    string? AiOperationId = null,
    string? AiCorrelationId = null,
    string? AiRiskClass = null,
    IReadOnlyList<string>? AiRiskActionClasses = null,
    string? AiPolicyReasonCode = null,
    string? AiClassifierVersion = null,
    string? AiRiskInputTuple = null,
    string? AiRequesterAuthorityClass = null,
    string? AiIndeterminateReason = null,
    string? AiPolicySnapshotId = null,
    string? AiPolicySnapshotVisibility = null,
    string? AiContextPackageId = null,
    string? AiContextPackageVersion = null,
    string? AiContextRedactionState = null,
    IReadOnlyList<string>? AiAuthorizedContextReferences = null,
    IReadOnlyList<string>? AiExcludedContextReasons = null,
    string? AiGeneratedSummaryRedactionState = null,
    string? AiGeneratedContentVisibility = null,
    string? AiCommandName = null,
    string? AiCommandAllowlistVersion = null,
    string? AiApprovalId = null,
    string? AiApprovalStatus = null,
    string? AiExecutionStatus = null,
    string? AiExecutionOutcomeCode = null,
    string? AiAuditOperationId = null,
    string? AiAuditStatus = null,
    string? AiFailureCode = null,
    string? AiRetryability = null,
    string? AiSafeNextAction = null,
    string? SupersedesAiOutcomeId = null,
    string? SupersededByAiOutcomeId = null,
    ProjectConversationItemStatusSummaryModel? StatusSummary = null,
    ProjectConversationItemClassificationModel? Classification = null,
    ProjectConversationDetectedIntentModel? DetectedIntent = null,
    ProjectConversationAiSummaryProvenanceModel? AiSummaryProvenance = null,
    IReadOnlyList<ProjectConversationReviewHistoryEntryModel>? ReviewHistory = null)
{
    public bool IsParticipant => string.Equals(Kind, "Participant", StringComparison.Ordinal);

    public bool IsAttachment => string.Equals(Kind, "Attachment", StringComparison.Ordinal);

    public bool IsSystemDecision => string.Equals(Kind, "SystemDecision", StringComparison.Ordinal);

    public bool IsApprovalEvent => string.Equals(Kind, "ApprovalEvent", StringComparison.Ordinal);

    public bool IsFailureState => string.Equals(Kind, "FailureState", StringComparison.Ordinal);

    public bool IsAiOutcome => string.Equals(Kind, "AiOutcome", StringComparison.Ordinal);
}

public sealed record ProjectConversationItemClassificationModel(
    string Kind,
    string KernelVersion,
    double ConfidenceScore,
    string MessageCode,
    IReadOnlyList<string> SourceEvidenceIds,
    string RedactionState);

public sealed record ProjectConversationDetectedIntentModel(
    string Summary,
    string ActionKind,
    IReadOnlyList<string> SourceEvidenceIds,
    string SafeNextAction,
    string MessageCode,
    string RedactionState);

public sealed record TaskIntentReviewModel(
    string ProjectId,
    string TaskIntentId,
    bool Available,
    string ReasonCode,
    string? SourceMessageContent,
    string? SourceMessageContentType,
    IReadOnlyList<TaskIntentAvailableTransitionModel> AvailableTransitions,
    IReadOnlyList<TaskIntentTransitionAuditSummaryModel> AuditHistory,
    string? CurrentState,
    long? SourceVersion,
    string CorrelationId,
    string RedactionState,
    string SchemaVersion);

public sealed record TaskIntentAvailableTransitionModel(
    string Transition,
    string Label,
    bool Enabled,
    string? DisabledReasonCode,
    bool RequiresPredecessorTaskIntentId);

public sealed record TaskIntentTransitionSelectionModel(
    string Transition,
    string? PredecessorTaskIntentId);

public sealed record TaskIntentTransitionAuditSummaryModel(
    string OperationId,
    string Status,
    string ActorId,
    DateTimeOffset DecidedAtUtc,
    string ReasonCode,
    string CorrelationId,
    string RedactionState);

public sealed record ProjectConversationAiSummaryProvenanceModel(
    string GeneratedBy,
    DateTimeOffset? GeneratedAtUtc,
    IReadOnlyList<string> SourceEvidenceIds,
    string? ContextPackageId,
    string? ContextPackageVersion,
    string RedactionState);

public sealed record ProjectConversationReviewHistoryEntryModel(
    string ReviewedResourceKind,
    string ReviewedResourceId,
    string ActionCode,
    string? DecisionCode,
    string? ActorKind,
    string? ActorLabel,
    DateTimeOffset ReviewedAtUtc,
    string? SurfaceOrigin,
    string? CorrelationId,
    string? OperationId,
    string RedactionState,
    string ReasonCode);

public sealed record ProjectConversationItemStatusSummaryModel(
    IReadOnlyList<ProjectConversationItemStatusFacetModel> Facets);

public sealed record ProjectConversationItemStatusFacetModel(
    string Domain,
    string Health,
    string SourceState,
    string MessageCode,
    string SafeNextAction,
    IReadOnlyDictionary<string, string> SafeMetadataIds,
    bool NotApplicable,
    string? OperationId,
    string? CompletionStatus,
    string? ProjectionStatus,
    string? AuditStatus,
    string? CorrelationId,
    int? RetryCount,
    string? TerminalReasonCode,
    string? ResponsibleOwnerRole,
    string? DuplicateSafetyState);
