namespace Hexalith.ChatBot.UI.State.ProjectConversation;

public sealed record ProjectAssociationWhyPanelModel(
    string ProjectId,
    string AssociationId,
    string IntakeId,
    string SourceMailboxId,
    string SourceConversationId,
    string? SourceThreadId,
    string LifecycleState,
    string Outcome,
    string ThresholdBand,
    double ConfidenceScore,
    string ThresholdPolicyVersion,
    string KernelVersion,
    DateTimeOffset DecisionTimestamp,
    string? DecisionActorId,
    string? DecisionActorType,
    string SourceProvenance,
    string RedactionState,
    string SchemaVersion,
    long SourceVersion,
    string CorrelationId,
    IReadOnlyList<string> ReasonCodes,
    IReadOnlyList<ProjectAssociationWhyEvidenceModel> Evidence,
    string? PriorProjectId,
    string? CorrectedProjectId,
    string? PredecessorAssociationId,
    string? SupersedesAssociationId,
    string? SupersededByAssociationId,
    string? SupersedingCorrectionId,
    string? SupersedingCorrectionLink,
    bool CorrectionPanelAvailable,
    string? PropagationStatus,
    string? DownstreamImpactStatus,
    bool IsCorrectedContextStale,
    string SafeNextAction)
{
    public bool IsEmpty => Evidence.Count == 0;
}
