<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Hexalith.ChatBot.Testing.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hexalith.ChatBot.Contracts\Hexalith.ChatBot.Contracts.csproj" />
  </ItemGroup>
</Project>
