using Hexalith.ChatBot.Contracts.Enums;

namespace Hexalith.ChatBot.Contracts.Queries;

/// <summary>
/// Metadata-only project conversation item derived from governed email association state.
/// </summary>
public sealed record ProjectConversationItem(
    string ItemId,
    ProjectConversationItemKind Kind,
    ProjectConversationActorKind ActorKind,
    string ActorLabel,
    DateTimeOffset OccurredAt,
    LifecycleState LifecycleState,
    AssociationThresholdBand ThresholdBand,
    double ConfidenceScore,
    string AssociationId,
    string SourceMailboxId,
    string? SourceProviderMessageId,
    string? InternetMessageId,
    string SourceConversationId,
    string? SourceThreadId,
    DateTimeOffset? SourceReceivedAtUtc,
    DateTimeOffset? SourceSentAtUtc,
    DateTimeOffset? SourceCreatedAtUtc,
    string? SourceTimezone,
    string? SourceProvenanceDisplayToken,
    string SourceProvenance,
    string RedactionState,
    string RetentionClass,
    string SchemaVersion,
    long SourceVersion,
    string CorrelationId,
    string? ProjectId = null,
    string? ProjectDisplayName = null,
    string? DecisionLabel = null,
    string? SafeNextAction = null,
    string? ParticipantResolutionId = null,
    string? SourceParticipantId = null,
    string? PartyId = null,
    ParticipantResolutionStatus? ParticipantStatus = null,
    ParticipantResolutionBlockedReason? ParticipantBlockedReason = null,
    ProjectConversationParticipantDisplayKind? ParticipantDisplayKind = null,
    string? ParticipantEvidenceReference = null,
    string? ParticipantEvidenceFingerprint = null,
    IReadOnlyList<ParticipantReviewAction>? ParticipantAllowedReviewActions = null,
    string? ParticipantRedactionState = null,
    string? SourceProviderAttachmentId = null,
    string? AttachmentDisplayName = null,
    string? AttachmentContentType = null,
    long? AttachmentSizeInBytes = null,
    ProjectConversationAttachmentStatus? AttachmentCaptureStatus = null,
    ProjectConversationAttachmentStatus? AttachmentStorageStatus = null,
    ProjectConversationAttachmentStatus? AttachmentScanStatus = null,
    string? AttachmentFolderId = null,
    string? AttachmentFileId = null,
    string? AttachmentDuplicateState = null,
    string? AttachmentRetryState = null,
    string? AttachmentAiContextEligibility = null,
    IReadOnlyList<string>? AttachmentAllowedActions = null,
    string? AttachmentRedactionState = null,
    AssociationDecisionKind? DecisionKind = null,
    string? DecisionActorId = null,
    string? DecisionActorType = null,
    DateTimeOffset? DecidedAtUtc = null,
    string? DecisionNoteRedactionState = null,
    string? SurfaceOrigin = null,
    string? PolicySnapshotVersion = null,
    IReadOnlyList<string>? EvidenceReferenceSummary = null,
    AssociationCorrectionKind? CorrectionKind = null,
    string? PriorProjectId = null,
    string? CorrectedProjectId = null,
    string? PredecessorAssociationId = null,
    string? SupersedesAssociationId = null,
    string? SupersededByAssociationId = null,
    string? CorrectionRationaleRedactionState = null,
    string? CorrectionActorId = null,
    string? CorrectionActorType = null,
    DateTimeOffset? CorrectedAtUtc = null,
    string? DownstreamImpactStatus = null,
    string? CorrectionId = null,
    string? WorkflowInstanceId = null,
    IReadOnlyList<string>? RequiredStoreKeys = null,
    IReadOnlyList<string>? CompletedStoreKeys = null,
    IReadOnlyList<string>? FailedStoreKeys = null,
    int? PropagationProgressNumerator = null,
    int? PropagationProgressDenominator = null,
    DateTimeOffset? PropagationStartedAtUtc = null,
    DateTimeOffset? PropagationCompletedAtUtc = null,
    DateTimeOffset? PropagationEstimatedCompletionAtUtc = null,
    string? PropagationStatus = null,
    bool? IsCorrectedContextStale = null,
    string? ResponsibleOwnerRole = null,
    string? ApprovalId = null,
    ApprovalEventKind? ApprovalEventKind = null,
    ApprovalStatus? ApprovalStatus = null,
    ApprovalDecisionKind? ApprovalDecisionKind = null,
    string? ApprovalRequesterId = null,
    string? ApprovalRequesterActorType = null,
    DateTimeOffset? ApprovalRequestedAtUtc = null,
    string? ApprovalDecisionActorId = null,
    string? ApprovalDecisionActorType = null,
    DateTimeOffset? ApprovalDecidedAtUtc = null,
    DateTimeOffset? ApprovalOutcomeAtUtc = null,
    string? ApprovalProposalId = null,
    string? ApprovalSourceMessageId = null,
    string? ApprovalSourceConversationItemId = null,
    string? ApprovalCommandName = null,
    string? ApprovalCommandAllowlistVersion = null,
    RiskClass? ApprovalRiskClass = null,
    IReadOnlyList<string>? ApprovalRiskActionClasses = null,
    AiActionRiskClass? ApprovalAiRiskClass = null,
    IReadOnlyList<string>? ApprovalAiRiskActionClasses = null,
    string? ApprovalAiRiskInputTuple = null,
    string? ApprovalPolicySnapshotId = null,
    string? ApprovalPolicySnapshotVisibility = null,
    IReadOnlyList<string>? ApprovalEvidenceReferences = null,
    IReadOnlyList<ApprovalEvidenceFreshness>? ApprovalEvidenceFreshnessStates = null,
    IReadOnlyList<string>? ApprovalAffectedResourceReferences = null,
    IReadOnlyList<string>? ApprovalRecipientReferences = null,
    string? ApprovalSenderAuthorityClass = null,
    string? ApprovalExpectedPostStateRedactionState = null,
    string? ApprovalActionSummaryRedactionState = null,
    string? ApprovalDecisionRationaleRedactionState = null,
    string? ApprovalAuthorityResult = null,
    string? ApprovalDisabledReason = null,
    string? ApprovalAuditOperationId = null,
    string? ApprovalAuditStatus = null,
    string? ApprovalCommandOutcomeStatus = null,
    string? ApprovalProjectedOutcomeItemId = null,
    string? ApprovalFailureCode = null,
    string? ApprovalRetryability = null,
    string? SupersedesApprovalId = null,
    string? SupersededByApprovalId = null,
    FailureStateKind? FailureStateKind = null,
    FailureStatus? FailureStatus = null,
    string? MessageCatalogCode = null,
    string? MessageCatalogVersion = null,
    string? MessageDetailVisibility = null,
    string? FailureCategory = null,
    string? FailureScope = null,
    string? FailureReasonCode = null,
    string? BlockedReason = null,
    bool? Retryable = null,
    int? RetryCount = null,
    int? MaxRetryCount = null,
    DateTimeOffset? NextRetryAtUtc = null,
    DateTimeOffset? LastRetryAtUtc = null,
    string? RetryOperationId = null,
    string? SupersedesWorkflowInstanceId = null,
    string? SupersededByWorkflowInstanceId = null,
    string? TaskId = null,
    string? OperationId = null,
    string? AuditOperationId = null,
    string? AuditStatus = null,
    string? ClientAction = null,
    string? DuplicateSafetyState = null,
    string? DuplicateSuppressionId = null,
    string? DependencyName = null,
    DateTimeOffset? DegradedUntilUtc = null,
    string? EscalationTargetRole = null,
    string? ReprocessCreatedWorkflowInstanceId = null,
    AiOutcomeKind? AiOutcomeKind = null,
    AiOutcomeStatus? AiOutcomeStatus = null,
    string? AiActorId = null,
    string? AiActorType = null,
    string? AiProposalId = null,
    string? AiRequestId = null,
    string? AiRequesterId = null,
    string? AiSourceConversationItemId = null,
    string? AiSourceMessageId = null,
    string? AiOperationId = null,
    string? AiCorrelationId = null,
    AiActionRiskClass? AiRiskClass = null,
    IReadOnlyList<string>? AiRiskActionClasses = null,
    string? AiPolicyReasonCode = null,
    string? AiClassifierVersion = null,
    string? AiRiskInputTuple = null,
    string? AiRequesterAuthorityClass = null,
    string? AiIndeterminateReason = null,
    string? AiPolicySnapshotId = null,
    string? AiPolicySnapshotVisibility = null,
    string? AiContextPackageId = null,
    string? AiContextPackageVersion = null,
    string? AiContextRedactionState = null,
    IReadOnlyList<string>? AiAuthorizedContextReferences = null,
    IReadOnlyList<string>? AiExcludedContextReasons = null,
    string? AiGeneratedSummaryRedactionState = null,
    string? AiGeneratedContentVisibility = null,
    string? AiCommandName = null,
    string? AiCommandAllowlistVersion = null,
    string? AiApprovalId = null,
    string? AiApprovalStatus = null,
    string? AiExecutionStatus = null,
    string? AiExecutionOutcomeCode = null,
    string? AiAuditOperationId = null,
    string? AiAuditStatus = null,
    string? AiFailureCode = null,
    string? AiRetryability = null,
    string? AiSafeNextAction = null,
    string? SupersedesAiOutcomeId = null,
    string? SupersededByAiOutcomeId = null,
    ProjectConversationItemStatusSummary? StatusSummary = null,
    ProjectConversationItemClassification? Classification = null,
    ProjectConversationDetectedIntent? DetectedIntent = null,
    ProjectConversationAiSummaryProvenance? AiSummaryProvenance = null,
    IReadOnlyList<ProjectConversationReviewHistoryEntry>? ReviewHistory = null);
