using System.Reflection;
using System.Runtime.Serialization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

using Hexalith.ChatBot.Client.Generated;
using Hexalith.ChatBot.Contracts.Commands;

using Shouldly;

namespace Hexalith.ChatBot.Client.Tests;

public static class ClientGenerationTests
{
    private static readonly string RepositoryRoot = LocateRepositoryRoot();

    [Fact]
    public static void NswagConfigurationShouldUseContractSpineAsOnlyInput()
    {
        string configurationPath = Path.Combine(RepositoryRoot, "src", "Hexalith.ChatBot.Client", "nswag.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(configurationPath));

        JsonElement fromDocument = document.RootElement.GetProperty("documentGenerator").GetProperty("fromDocument");
        JsonElement generator = document.RootElement.GetProperty("codeGenerators").GetProperty("openApiToCSharpClient");

        fromDocument.GetProperty("url").GetString().ShouldBe("../../src/Hexalith.ChatBot.Contracts/openapi/hexalith.chatbot.v1.yaml");
        generator.GetProperty("newLineBehavior").GetString().ShouldBe("LF");
        generator.GetProperty("output").GetString().ShouldBe("Generated/HexalithChatBotClient.g.cs");
        generator.GetProperty("namespace").GetString().ShouldBe("Hexalith.ChatBot.Client.Generated");
        generator.GetProperty("injectHttpClient").GetBoolean().ShouldBeTrue();
        generator.GetProperty("disposeHttpClient").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateSyncMethods").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateClientInterfaces").GetBoolean().ShouldBeTrue();
        generator.GetProperty("useBaseUrl").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateOptionalPropertiesAsNullable").GetBoolean().ShouldBeTrue();
        generator.GetProperty("generateNullableReferenceTypes").GetBoolean().ShouldBeTrue();
    }

    [Fact]
    public static void GeneratedOutputShouldExistUnderGeneratedAndCarrySafeProvenance()
    {
        string generatedPath = GeneratedClientPath();
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated>");
        generated.ShouldContain("NSwag");
        generated.ShouldContain("namespace Hexalith.ChatBot.Client.Generated");
        generated.ShouldNotContain(RepositoryRoot, Case.Insensitive);
        generated.ShouldNotContain(DateTimeOffset.UtcNow.Year.ToString(), Case.Insensitive);
        generated.ShouldNotContain("Dapr", Case.Insensitive);
        generated.ShouldNotContain("EventStore", Case.Insensitive);
        generated.ShouldNotContain("CommandGateway", Case.Insensitive);
    }

    [Fact]
    public static void GeneratedOutputHashShouldMatchCheckedInFreshnessFixture()
    {
        string expected = File.ReadAllText(Path.Combine(RepositoryRoot, "tests", "fixtures", "hexalith-chatbot-generated-client.sha256")).Trim();
        string actual = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(File.ReadAllText(GeneratedClientPath())))).ToLowerInvariant();

        actual.ShouldBe(expected);
    }

    [Fact]
    public static void FacadeShouldExposeTypedCommandAndStatusMethodsOnly()
    {
        MethodInfo submit = typeof(IChatBotClient).GetMethod(nameof(IChatBotClient.SubmitAsync)).ShouldNotBeNull();
        ParameterInfo[] parameters = submit.GetParameters();

        parameters[0].ParameterType.ShouldBe(typeof(IChatBotCommand));
        typeof(IChatBotClient).GetMethod(nameof(IChatBotClient.GetOperationStatusAsync)).ShouldNotBeNull()
            .ReturnType.ShouldBe(typeof(Task<OperationStatus>));
        typeof(IChatBotClient).GetMethod(nameof(IChatBotClient.GetOperationAuditHistoryAsync)).ShouldNotBeNull()
            .ReturnType.ShouldBe(typeof(Task<OperationAuditHistory>));
        typeof(IChatBotClient).GetMethod(nameof(IChatBotClient.GetAssociationRoutingStatusAsync)).ShouldNotBeNull()
            .ReturnType.ShouldBe(typeof(Task<AssociationRoutingStatus>));
        typeof(IChatBotClient).GetMethod(nameof(IChatBotClient.GetProjectConversationAsync)).ShouldNotBeNull()
            .ReturnType.ShouldBe(typeof(Task<ProjectConversationResponse>));
        string[] parameterTypeNames = parameters.Select(static parameter => parameter.ParameterType.FullName ?? string.Empty).ToArray();
        parameterTypeNames.Any(static type => type.Contains("Dapr", StringComparison.Ordinal)).ShouldBeFalse();
        parameterTypeNames.Any(static type => type.Contains("EventStore", StringComparison.Ordinal)).ShouldBeFalse();
    }

    [Fact]
    public static async Task FacadeShouldValidateAdapterSuppliedContractMetadata()
    {
        RecordingTransportClient transport = new();
        ChatBotClient client = new(transport);

        await client.SubmitAsync(
            new StartConversationIntake(),
            "01arz3ndektsv4rrffq69g5faw",
            "01arz3ndektsv4rrffq69g5fax",
            cancellationToken: TestContext.Current.CancellationToken);

        transport.LastCorrelationId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAW");
        transport.LastTaskId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAX");
        transport.LastBody.ShouldNotBeNull().CommandType.ShouldBe(nameof(StartConversationIntake));

        OperationStatus status = await client.GetOperationStatusAsync(
            "01arz3ndektsv4rrffq69g5fax",
            "01arz3ndektsv4rrffq69g5faw",
            cancellationToken: TestContext.Current.CancellationToken);

        transport.LastOperationId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAX");
        transport.LastCorrelationId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAW");
        status.CompletionStatus.ShouldBe(OperationCompletionStatus.AcceptedProjectionPending);

        OperationAuditHistory auditHistory = await client.GetOperationAuditHistoryAsync(
            "01arz3ndektsv4rrffq69g5fax",
            "01arz3ndektsv4rrffq69g5faw",
            cancellationToken: TestContext.Current.CancellationToken);

        transport.LastOperationId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAX");
        auditHistory.AuditStatus.ShouldBe(OperationAuditStatus.Committed);

        AssociationRoutingStatus associationStatus = await client.GetAssociationRoutingStatusAsync(
            "01arz3ndektsv4rrffq69g5faz",
            "01arz3ndektsv4rrffq69g5faw",
            cancellationToken: TestContext.Current.CancellationToken);

        transport.LastAssociationId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAZ");
        associationStatus.LifecycleState.ShouldBe(LifecycleState.NeedsReview);

        ProjectConversationResponse conversation = await client.GetProjectConversationAsync(
            "project-001",
            correlationId: "01arz3ndektsv4rrffq69g5faw",
            cancellationToken: TestContext.Current.CancellationToken);

        transport.LastProjectId.ShouldBe("project-001");
        conversation.ProjectId.ShouldBe("project-001");

        Should.Throw<ArgumentException>(() => client.SubmitAsync(new StartConversationIntake(), "not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.SubmitAsync(new StartConversationIntake(), taskId: "not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.SubmitAsync(new StartConversationIntakeCommand()));
        Should.Throw<ArgumentException>(() => client.GetOperationStatusAsync("not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.GetOperationAuditHistoryAsync("not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.GetAssociationRoutingStatusAsync("not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.GetProjectConversationAsync("unsafe project value"));
    }

    [Fact]
    public static async Task SubmitAsyncShouldMapEveryDeclaredSurfaceOriginOntoTheWireRequest()
    {
        // First-party adapters declare their surface at the boundary; the facade must thread that
        // declaration onto the generated wire request (the closed Contracts enum maps member-for-member
        // onto the generated SurfaceOrigin enum) so it travels to the gateway and into the audit envelope.
        foreach (Contracts.Enums.ChatBotSurfaceOrigin origin in Enum.GetValues<Contracts.Enums.ChatBotSurfaceOrigin>())
        {
            RecordingTransportClient transport = new();
            ChatBotClient client = new(transport);

            await client.SubmitAsync(
                new StartConversationIntake(),
                origin: origin,
                cancellationToken: TestContext.Current.CancellationToken);

            SurfaceOrigin expected = Enum.Parse<SurfaceOrigin>(origin.ToString());
            transport.LastBody.ShouldNotBeNull().Origin.ShouldBe(expected);
        }
    }

    [Fact]
    public static async Task SubmitAsyncWithoutDeclaredOriginShouldDefaultToApiOnTheWire()
    {
        RecordingTransportClient transport = new();
        ChatBotClient client = new(transport);

        await client.SubmitAsync(
            new StartConversationIntake(),
            cancellationToken: TestContext.Current.CancellationToken);

        transport.LastBody.ShouldNotBeNull().Origin.ShouldBe(SurfaceOrigin.Api);
    }

    [Fact]
    public static void GeneratedOptionalPropertiesShouldNotDefaultIntoAdapterPayloads()
    {
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.ActorType)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(ActorType?));
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.RiskClass)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(RiskClass?));
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.ThresholdBand)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(ThresholdBand?));
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.Origin)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(SurfaceOrigin?));
        typeof(CommandSubmissionResponse).GetProperty(nameof(CommandSubmissionResponse.TaskId)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(string));
    }

    [Fact]
    public static void GeneratedLifecycleStateShouldUseCanonicalWireValuesInOrder()
    {
        Enum.GetNames<LifecycleState>().ShouldBe(
            [
                "Received",
                "Proposed",
                "Associated",
                "Rejected",
                "Deferred",
                "NeedsReview",
                "Failed",
                "Skipped",
                "Corrected",
                "Correcting",
                "CorrectionDelayed",
            ],
            ignoreOrder: false);

        Enum.GetValues<LifecycleState>()
            .Select(static value => typeof(LifecycleState)
                .GetField(value.ToString())
                .ShouldNotBeNull()
                .GetCustomAttribute<EnumMemberAttribute>()
                .ShouldNotBeNull()
                .Value)
            .ShouldBe(
                [
                    "Received",
                    "Proposed",
                    "Associated",
                    "Rejected",
                    "Deferred",
                    "NeedsReview",
                    "Failed",
                    "Skipped",
                    "Corrected",
                    "Correcting",
                    "Correction-delayed",
                ],
                ignoreOrder: false);
    }

    [Fact]
    public static void GeneratedProblemClientActionShouldUseCatalogWireValues()
    {
        Enum.GetNames<ProblemDetailsClientAction>().ShouldBe(
            [
                "Authenticate",
                "RetryLater",
                "RequestAccess",
                "Escalate",
                "Dismiss",
                "CorrectRequest",
                "None",
            ],
            ignoreOrder: false);

        Enum.GetValues<ProblemDetailsClientAction>()
            .Select(static value => typeof(ProblemDetailsClientAction)
                .GetField(value.ToString())
                .ShouldNotBeNull()
                .GetCustomAttribute<EnumMemberAttribute>()
                .ShouldNotBeNull()
                .Value)
            .ShouldBe(
                [
                    "authenticate",
                    "retry-later",
                    "request-access",
                    "escalate",
                    "dismiss",
                    "correct-request",
                    "none",
                ],
                ignoreOrder: false);
    }

    [Fact]
    public static void GeneratedOperationStatusEnumsShouldUseCanonicalWireValuesAndKeepPendingDistinctFromCompleted()
    {
        Enum.GetNames<OperationCompletionStatus>().ShouldBe(
            ["AcceptedProjectionPending", "Completed", "Failed"],
            ignoreOrder: false);

        Enum.GetValues<OperationCompletionStatus>()
            .Select(static value => typeof(OperationCompletionStatus)
                .GetField(value.ToString())
                .ShouldNotBeNull()
                .GetCustomAttribute<EnumMemberAttribute>()
                .ShouldNotBeNull()
                .Value)
            .ShouldBe(
                ["accepted-projection-pending", "completed", "failed"],
                ignoreOrder: false);

        // Never-a-false-Done: the projection-pending and completed states must remain distinct members with
        // distinct wire values so a pending operation can never serialize as completed.
        OperationCompletionStatus.AcceptedProjectionPending.ShouldNotBe(OperationCompletionStatus.Completed);
        GetWireValue(OperationCompletionStatus.AcceptedProjectionPending)
            .ShouldNotBe(GetWireValue(OperationCompletionStatus.Completed));

        Enum.GetNames<OperationAuditStatus>().ShouldBe(
            ["Committed", "Reconciling"],
            ignoreOrder: false);

        Enum.GetValues<OperationAuditStatus>()
            .Select(static value => typeof(OperationAuditStatus)
                .GetField(value.ToString())
                .ShouldNotBeNull()
                .GetCustomAttribute<EnumMemberAttribute>()
                .ShouldNotBeNull()
                .Value)
            .ShouldBe(
                ["committed", "reconciling"],
                ignoreOrder: false);
    }

    [Fact]
    public static void GeneratedAssociationRoutingStatusShouldExposeNeedsReviewFields()
    {
        typeof(AssociationRoutingStatus).GetProperty(nameof(AssociationRoutingStatus.LifecycleState))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(LifecycleState));
        typeof(AssociationRoutingStatus).GetProperty(nameof(AssociationRoutingStatus.Candidates))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(ICollection<Hexalith.ChatBot.Client.Generated.AssociationCandidate>));
        typeof(ChatBotMessageCode).GetMember(nameof(ChatBotMessageCode.Association_ambiguous_routed))
            .ShouldHaveSingleItem();
    }

    [Fact]
    public static void GeneratedProjectConversationShouldExposeCursorAndSystemDecisionContracts()
    {
        typeof(ProjectConversationResponse).GetProperty(nameof(ProjectConversationResponse.Items))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(ICollection<ProjectConversationItem>));
        typeof(ProjectConversationResponse).GetProperty(nameof(ProjectConversationResponse.Page))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(ProjectConversationCursorPage));
        typeof(ProjectConversationItem).GetProperty(nameof(ProjectConversationItem.SourceProviderMessageId))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(string));
        typeof(ProjectConversationItem).GetProperty(nameof(ProjectConversationItem.InternetMessageId))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(string));
        typeof(ProjectConversationItem).GetProperty(nameof(ProjectConversationItem.SourceReceivedAtUtc))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(DateTimeOffset?));
        typeof(ProjectConversationItem).GetProperty(nameof(ProjectConversationItem.SourceProvenanceDisplayToken))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(string));
        typeof(ProjectConversationItem).GetProperty(nameof(ProjectConversationItem.ParticipantResolutionId))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(string));
        typeof(ProjectConversationItem).GetProperty(nameof(ProjectConversationItem.ParticipantAllowedReviewActions))
            .ShouldNotBeNull()
            .PropertyType.ShouldBe(typeof(ICollection<ParticipantReviewAction>));
        typeof(ProjectConversationItem).GetProperty("SourceContext").ShouldBeNull();
        typeof(ProjectConversationItem).GetProperty("AddressEvidence").ShouldBeNull();
        GetWireValue(ProjectConversationItemKind.SystemDecision).ShouldBe("system-decision");
        GetWireValue(ProjectConversationItemKind.Participant).ShouldBe("participant");
        GetWireValue(ProjectConversationActorKind.SystemDecision).ShouldBe("system-decision");
        GetWireValue(ProjectConversationActorKind.InternalParticipant).ShouldBe("internal-participant");
        GetWireValue(ProjectConversationParticipantDisplayKind.ExternalParticipant).ShouldBe("external-participant");
    }

    [Fact]
    public static void ClientProjectShouldGenerateBeforeCompileWithoutInlinePackageVersions()
    {
        string projectPath = Path.Combine(RepositoryRoot, "src", "Hexalith.ChatBot.Client", "Hexalith.ChatBot.Client.csproj");
        string project = File.ReadAllText(projectPath);

        project.ShouldContain("NSwag.MSBuild");
        project.ShouldContain("GenerateHexalithChatBotClient");
        project.ShouldContain("BeforeTargets=\"BeforeCompile\"");
        project.ShouldNotContain("Version=");
    }

    private static string? GetWireValue<T>(T value)
        where T : struct, Enum
        => typeof(T)
            .GetField(value.ToString())
            .ShouldNotBeNull()
            .GetCustomAttribute<EnumMemberAttribute>()
            .ShouldNotBeNull()
            .Value;

    private static string GeneratedClientPath()
        => Path.Combine(RepositoryRoot, "src", "Hexalith.ChatBot.Client", "Generated", "HexalithChatBotClient.g.cs");

    private static string LocateRepositoryRoot()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Hexalith.ChatBot.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Could not locate repository root.");
    }

    private sealed record StartConversationIntake : IChatBotCommand;

    private sealed record StartConversationIntakeCommand : IChatBotCommand;

    private sealed class RecordingTransportClient : IClient
    {
        public string? LastCorrelationId { get; private set; }

        public string? LastTaskId { get; private set; }

        public string? LastOperationId { get; private set; }

        public string? LastAssociationId { get; private set; }

        public string? LastProjectId { get; private set; }

        public CommandSubmissionRequest? LastBody { get; private set; }

        public Task<CommandSubmissionResponse> SubmitCommandAsync(string? x_Correlation_Id, string? x_Hexalith_Task_Id, CommandSubmissionRequest body)
            => SubmitCommandAsync(x_Correlation_Id, x_Hexalith_Task_Id, body, CancellationToken.None);

        public Task<CommandSubmissionResponse> SubmitCommandAsync(string? x_Correlation_Id, string? x_Hexalith_Task_Id, CommandSubmissionRequest body, CancellationToken cancellationToken)
        {
            LastCorrelationId = x_Correlation_Id;
            LastTaskId = x_Hexalith_Task_Id;
            LastBody = body;

            return Task.FromResult(new CommandSubmissionResponse
            {
                CommandId = body.CommandId,
                CorrelationId = x_Correlation_Id ?? string.Empty,
                TaskId = x_Hexalith_Task_Id,
                LifecycleState = Enum.Parse<LifecycleState>("Proposed"),
                AcceptedAt = DateTimeOffset.UtcNow,
            });
        }

        public Task<OperationStatus> GetOperationStatusAsync(string operationId, string? x_Correlation_Id, string? x_Hexalith_Task_Id)
            => GetOperationStatusAsync(operationId, x_Correlation_Id, x_Hexalith_Task_Id, CancellationToken.None);

        public Task<OperationStatus> GetOperationStatusAsync(
            string operationId,
            string? x_Correlation_Id,
            string? x_Hexalith_Task_Id,
            CancellationToken cancellationToken)
        {
            LastOperationId = operationId;
            LastCorrelationId = x_Correlation_Id;
            LastTaskId = x_Hexalith_Task_Id;

            return Task.FromResult(new OperationStatus
            {
                OperationId = operationId,
                CommandId = "01ARZ3NDEKTSV4RRFFQ69G5FAY",
                CorrelationId = x_Correlation_Id ?? string.Empty,
                LifecycleState = LifecycleState.Proposed,
                RetryCount = 0,
                CompletionStatus = OperationCompletionStatus.AcceptedProjectionPending,
                AuditStatus = OperationAuditStatus.Committed,
                PartialOutputs = new OperationStatusPartialOutputs
                {
                    AcceptedAt = DateTimeOffset.UtcNow,
                    CompletionStatus = OperationCompletionStatus.AcceptedProjectionPending,
                    AuditStatus = OperationAuditStatus.Committed,
                },
                SafeNextActions = [ChatBotMessageNextAction.None],
                AcceptedAt = DateTimeOffset.UtcNow,
                LastUpdatedAt = DateTimeOffset.UtcNow,
            });
        }

        public Task<OperationAuditHistory> GetOperationAuditHistoryAsync(string operationId, string? x_Correlation_Id, string? x_Hexalith_Task_Id)
            => GetOperationAuditHistoryAsync(operationId, x_Correlation_Id, x_Hexalith_Task_Id, CancellationToken.None);

        public Task<OperationAuditHistory> GetOperationAuditHistoryAsync(
            string operationId,
            string? x_Correlation_Id,
            string? x_Hexalith_Task_Id,
            CancellationToken cancellationToken)
        {
            LastOperationId = operationId;
            LastCorrelationId = x_Correlation_Id;
            LastTaskId = x_Hexalith_Task_Id;

            return Task.FromResult(new OperationAuditHistory
            {
                OperationId = operationId,
                AuditStatus = OperationAuditStatus.Committed,
                Entries = [],
            });
        }

        public Task<AssociationRoutingStatus> GetAssociationRoutingStatusAsync(string associationId, string? x_Correlation_Id, string? x_Hexalith_Task_Id)
            => GetAssociationRoutingStatusAsync(associationId, x_Correlation_Id, x_Hexalith_Task_Id, CancellationToken.None);

        public Task<AssociationRoutingStatus> GetAssociationRoutingStatusAsync(
            string associationId,
            string? x_Correlation_Id,
            string? x_Hexalith_Task_Id,
            CancellationToken cancellationToken)
        {
            LastAssociationId = associationId;
            LastCorrelationId = x_Correlation_Id;
            LastTaskId = x_Hexalith_Task_Id;

            return Task.FromResult(new AssociationRoutingStatus
            {
                AssociationId = associationId,
                IntakeId = "01ARZ3NDEKTSV4RRFFQ69G5FBA",
                SourceMailboxId = "mailbox",
                SourceConversationId = "conversation",
                LifecycleState = LifecycleState.NeedsReview,
                Outcome = AssociationScoringOutcome.CandidatesGenerated,
                ThresholdBand = AssociationThresholdBand.Ambiguous,
                ConfidenceScore = 0.64,
                ReasonCodes = [AssociationReasonCode.MultipleAuthorizedCandidates],
                Candidates = [],
                Exclusions = [],
                ThresholdPolicyVersion = "association-thresholds.m0.default.v1",
                EvidenceRefs = [],
                KernelVersion = "association-deterministic.kernel.m0.v1",
                DetectedAt = DateTimeOffset.UtcNow,
                SourceProvenance = AssociationRoutingStatusSourceProvenance.M365MailboxIntake,
                RedactionState = AssociationRoutingStatusRedactionState.Metadata_only,
                RetentionClass = AssociationRoutingStatusRetentionClass.Collaboration_input,
                SchemaVersion = "chatbot.association-routing-status.v1",
                CorrelationId = x_Correlation_Id ?? string.Empty,
                DisabledActionReasonCodes = ["decision-command-not-available"],
                NextActionReasonCodes = [ChatBotMessageCode.Association_ambiguous_routed],
            });
        }

        public Task<ProjectConversationResponse> GetProjectConversationAsync(
            string projectId,
            string? cursor,
            int? pageSize,
            string? x_Correlation_Id,
            string? x_Hexalith_Task_Id)
            => GetProjectConversationAsync(projectId, cursor, pageSize, x_Correlation_Id, x_Hexalith_Task_Id, CancellationToken.None);

        public Task<ProjectConversationResponse> GetProjectConversationAsync(
            string projectId,
            string? cursor,
            int? pageSize,
            string? x_Correlation_Id,
            string? x_Hexalith_Task_Id,
            CancellationToken cancellationToken)
        {
            LastProjectId = projectId;
            LastCorrelationId = x_Correlation_Id;
            LastTaskId = x_Hexalith_Task_Id;

            return Task.FromResult(new ProjectConversationResponse
            {
                ProjectId = projectId,
                ProjectDisplayName = "Authorized Project",
                Status = ProjectConversationReadStatus.Current,
                ConversationState = LifecycleState.Associated,
                Items = [],
                Page = new ProjectConversationCursorPage { HasMore = false, PageSize = pageSize ?? 25 },
                SourceProvenance = ProjectConversationResponseSourceProvenance.M365MailboxIntake,
                RedactionState = ProjectConversationResponseRedactionState.Metadata_only,
                RetentionClass = ProjectConversationResponseRetentionClass.Collaboration_input,
                SchemaVersion = ProjectConversationResponseSchemaVersion.Chatbot_projectConversationResponse_v1,
                CorrelationId = x_Correlation_Id ?? string.Empty,
                SafeNextAction = "none",
            });
        }
    }
}
