using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

using Hexalith.ChatBot.Client.Generated;
using Hexalith.ChatBot.Contracts.Commands;

using Shouldly;

namespace Hexalith.ChatBot.Client.Tests;

public static class ClientGenerationTests
{
    private static readonly string RepositoryRoot = LocateRepositoryRoot();

    [Fact]
    public static void NswagConfigurationShouldUseContractSpineAsOnlyInput()
    {
        string configurationPath = Path.Combine(RepositoryRoot, "src", "Hexalith.ChatBot.Client", "nswag.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(configurationPath));

        JsonElement fromDocument = document.RootElement.GetProperty("documentGenerator").GetProperty("fromDocument");
        JsonElement generator = document.RootElement.GetProperty("codeGenerators").GetProperty("openApiToCSharpClient");

        fromDocument.GetProperty("url").GetString().ShouldBe("../../src/Hexalith.ChatBot.Contracts/openapi/hexalith.chatbot.v1.yaml");
        generator.GetProperty("newLineBehavior").GetString().ShouldBe("LF");
        generator.GetProperty("output").GetString().ShouldBe("Generated/HexalithChatBotClient.g.cs");
        generator.GetProperty("namespace").GetString().ShouldBe("Hexalith.ChatBot.Client.Generated");
        generator.GetProperty("injectHttpClient").GetBoolean().ShouldBeTrue();
        generator.GetProperty("disposeHttpClient").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateSyncMethods").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateClientInterfaces").GetBoolean().ShouldBeTrue();
        generator.GetProperty("useBaseUrl").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateOptionalPropertiesAsNullable").GetBoolean().ShouldBeTrue();
        generator.GetProperty("generateNullableReferenceTypes").GetBoolean().ShouldBeTrue();
    }

    [Fact]
    public static void GeneratedOutputShouldExistUnderGeneratedAndCarrySafeProvenance()
    {
        string generatedPath = GeneratedClientPath();
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated>");
        generated.ShouldContain("NSwag");
        generated.ShouldContain("namespace Hexalith.ChatBot.Client.Generated");
        generated.ShouldNotContain(RepositoryRoot, Case.Insensitive);
        generated.ShouldNotContain(DateTimeOffset.UtcNow.Year.ToString(), Case.Insensitive);
        generated.ShouldNotContain("Dapr", Case.Insensitive);
        generated.ShouldNotContain("EventStore", Case.Insensitive);
        generated.ShouldNotContain("CommandGateway", Case.Insensitive);
    }

    [Fact]
    public static void GeneratedOutputHashShouldMatchCheckedInFreshnessFixture()
    {
        string expected = File.ReadAllText(Path.Combine(RepositoryRoot, "tests", "fixtures", "hexalith-chatbot-generated-client.sha256")).Trim();
        string actual = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(File.ReadAllText(GeneratedClientPath())))).ToLowerInvariant();

        actual.ShouldBe(expected);
    }

    [Fact]
    public static void FacadeShouldExposeSubmitAsyncForTypedCommandsOnly()
    {
        MethodInfo submit = typeof(IChatBotClient).GetMethod(nameof(IChatBotClient.SubmitAsync)).ShouldNotBeNull();
        ParameterInfo[] parameters = submit.GetParameters();

        parameters[0].ParameterType.ShouldBe(typeof(IChatBotCommand));
        string[] parameterTypeNames = parameters.Select(static parameter => parameter.ParameterType.FullName ?? string.Empty).ToArray();
        parameterTypeNames.Any(static type => type.Contains("Dapr", StringComparison.Ordinal)).ShouldBeFalse();
        parameterTypeNames.Any(static type => type.Contains("EventStore", StringComparison.Ordinal)).ShouldBeFalse();
    }

    [Fact]
    public static async Task FacadeShouldValidateAdapterSuppliedContractMetadata()
    {
        RecordingTransportClient transport = new();
        ChatBotClient client = new(transport);

        await client.SubmitAsync(
            new StartConversationIntake(),
            "01arz3ndektsv4rrffq69g5faw",
            "01arz3ndektsv4rrffq69g5fax",
            TestContext.Current.CancellationToken);

        transport.LastCorrelationId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAW");
        transport.LastTaskId.ShouldBe("01ARZ3NDEKTSV4RRFFQ69G5FAX");
        transport.LastBody.ShouldNotBeNull().CommandType.ShouldBe(nameof(StartConversationIntake));

        Should.Throw<ArgumentException>(() => client.SubmitAsync(new StartConversationIntake(), "not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.SubmitAsync(new StartConversationIntake(), taskId: "not-a-ulid"));
        Should.Throw<ArgumentException>(() => client.SubmitAsync(new StartConversationIntakeCommand()));
    }

    [Fact]
    public static void GeneratedOptionalPropertiesShouldNotDefaultIntoAdapterPayloads()
    {
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.ActorType)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(ActorType?));
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.RiskClass)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(RiskClass?));
        typeof(CommandSubmissionRequest).GetProperty(nameof(CommandSubmissionRequest.ThresholdBand)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(ThresholdBand?));
        typeof(CommandSubmissionResponse).GetProperty(nameof(CommandSubmissionResponse.TaskId)).ShouldNotBeNull().PropertyType.ShouldBe(typeof(string));
    }

    [Fact]
    public static void ClientProjectShouldGenerateBeforeCompileWithoutInlinePackageVersions()
    {
        string projectPath = Path.Combine(RepositoryRoot, "src", "Hexalith.ChatBot.Client", "Hexalith.ChatBot.Client.csproj");
        string project = File.ReadAllText(projectPath);

        project.ShouldContain("NSwag.MSBuild");
        project.ShouldContain("GenerateHexalithChatBotClient");
        project.ShouldContain("BeforeTargets=\"BeforeCompile\"");
        project.ShouldNotContain("Version=");
    }

    private static string GeneratedClientPath()
        => Path.Combine(RepositoryRoot, "src", "Hexalith.ChatBot.Client", "Generated", "HexalithChatBotClient.g.cs");

    private static string LocateRepositoryRoot()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Hexalith.ChatBot.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Could not locate repository root.");
    }

    private sealed record StartConversationIntake : IChatBotCommand;

    private sealed record StartConversationIntakeCommand : IChatBotCommand;

    private sealed class RecordingTransportClient : IClient
    {
        public string? LastCorrelationId { get; private set; }

        public string? LastTaskId { get; private set; }

        public CommandSubmissionRequest? LastBody { get; private set; }

        public Task<CommandSubmissionResponse> SubmitCommandAsync(string? x_Correlation_Id, string? x_Hexalith_Task_Id, CommandSubmissionRequest body)
            => SubmitCommandAsync(x_Correlation_Id, x_Hexalith_Task_Id, body, CancellationToken.None);

        public Task<CommandSubmissionResponse> SubmitCommandAsync(string? x_Correlation_Id, string? x_Hexalith_Task_Id, CommandSubmissionRequest body, CancellationToken cancellationToken)
        {
            LastCorrelationId = x_Correlation_Id;
            LastTaskId = x_Hexalith_Task_Id;
            LastBody = body;

            return Task.FromResult(new CommandSubmissionResponse
            {
                CommandId = body.CommandId,
                CorrelationId = x_Correlation_Id ?? string.Empty,
                TaskId = x_Hexalith_Task_Id,
                LifecycleState = LifecycleState.Accepted,
                AcceptedAt = DateTimeOffset.UtcNow,
            });
        }
    }
}
